[package]
name = "octal_to_hex"
version = "0.1.0"
authors = ["<Alanis Pereyra> <alaniswagner14@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
